server:
  port: 8090
spring:
  application:
    name: segmentation
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/segmentation
    username: postgres
    password: 1331
    driver-class-name: org.postgresql.Driver
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger
    packages-to-scan: com.vk.itmo.segmentation