name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5 
          --health-start-period 30s

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: BootRun Application
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/test
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_PASSWORD: test
        run: ./gradlew bootRun &

      - name: Run Tests
        run: ./gradlew test

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the commit hash
        id: commit_hash
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t l1zail/segmentation:${{ env.COMMIT_HASH }} -f Dockerfile .

      - name: Push Docker image
        run: |
          docker push l1zail/segmentation:${{ env.COMMIT_HASH }}

      - name: Tag Docker image as latest
        run: |
          docker tag l1zail/segmentation:${{ env.COMMIT_HASH }} l1zail/java-lab2:latest

      - name: Push Docker image as latest
        run: |
          docker push l1zail/segmentation:latest
